# Generated by Django 5.1.4 on 2024-12-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_like_unique_together_remove_post_is_liked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
    ]
