# Generated by Django 5.1.4 on 2024-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='network/'),
        ),
    ]
